const router = require('express').Router();
const { getAll, getOne, create, update, remove, toggleEmergency } = require('../controllers/trafficController');
const { protect } = require('../middleware/authMiddleware');
router.use(protect);
router.get('/', getAll);
router.get('/:id', getOne);
router.post('/', create);
router.put('/:id', update);
router.delete('/:id', remove);
router.put('/:id/emergency', toggleEmergency);
module.exports = router;
